# Generated by Django 4.0.4 on 2022-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_id', models.IntegerField(verbose_name='id')),
                ('second_id', models.IntegerField(verbose_name='Заказ №')),
                ('price_usd', models.FloatField(verbose_name='стоимость,$')),
                ('price_rub', models.FloatField(verbose_name='стоимость,₽')),
                ('date', models.DateField(verbose_name='срок поставки')),
            ],
            options={
                'ordering': ('-first_id',),
            },
        ),
    ]
